Fix project limits calculation.
Cast Decimal to Int in _get_counts, similar to _get_counts_in_db.

SQLalchemy func.sum() returns Decimal on MySQL. When the usage limits
are calculated unless explicetely converted to Int we end up with
Decimal objects that cannot be JSONified and thus causing
ValueError: Circular reference detected.