Revert "vmware: Move deviceChange in clone operation"
This reverts commit ba7bcc11884fdb3e5f6311aa4842bc502292bb20.

It doesn't work. When creating an image from a server, the operation
always fails with

  VimFaultException: The operation is not allowed in the current state.

(cherry picked from commit f90793873c2b5306a1916460ad43be0181adae92)