fixup! Sync states when in SUSPENDED state
Using `vm_state` instead of `vm_states` is a bug which leads to:

	AttributeError
	'unicode' object has no attribute 'ACTIVE'

(cherry picked from commit fe56b81cacda608c16468fcf4385f66b79fa84a7)