vmware: vm_ref cache healing handles empty cache
If an instance cannot be found on VMware-side during an operation, we
try to fetch the new moref and retry the operation. This can fail, if we
passed in a moref explicitly and thus didn't look into the cache and the cache
contains no value for the instance - this would raise an AttributeError.

We fix this by checking the cache actually contained a value and return
without retry if it didn't, as we cannot tell if the vm_ref passed
belongs to the instance or not.

	AttributeError: 'NoneType' object has no attribute 'value'
	  ...
	  File "nova/compute/manager.py", line 2975, in start_instance
		self._power_on(context, instance)
	  File "nova/compute/manager.py", line 2945, in _power_on
		block_device_info)
	  File "nova/virt/vmwareapi/driver.py", line 633, in power_on
		self._vmops.power_on(instance)
	  File "nova/virt/vmwareapi/vmops.py", line 1936, in power_on
		vm_util.power_on_instance(self._session, instance)
	  File "nova/virt/vmwareapi/vm_util.py", line 326, in wrapper
		if obj != vm_ref.value:

Change-Id: I093a0c6260cb19478c7c25c630e453dd77d39f40