Fix test env by pinning bandit <1.6
We run into failures when installing the virtualenv for testing, because
newer bandit versions don't support Python 2.7 anymore. Pinning it to a
supported version fixes this.

  ERROR: Package 'bandit' requires a different Python: 2.7.18 not in '>=3.5'

Change-Id: I693d3aadfe90990b8b3e1aee329c3a230d3d8908