fix some quota-related test failures
Since we changed the quota-implementation, we have to change this
test-case to define that it uses the database. Otherwise, we end up with
errors like this:

    2020-02-10 13:07:44,164 ERROR [nova.api.openstack.wsgi] Unexpected exception in API method
    Traceback (most recent call last):
      File "nova/api/openstack/wsgi.py", line 788, in wrapped
        return f(*args, **kwargs)
      File "nova/api/openstack/compute/quota_sets.py", line 113, in show
        return self._show(req, id, [])
      File "nova/api/validation/__init__.py", line 181, in wrapper
        return func(*args, **kwargs)
      File "nova/api/openstack/compute/quota_sets.py", line 136, in _show
        filtered_quotas=filtered_quotas)
      File "nova/api/openstack/compute/quota_sets.py", line 58, in _format_quota_set
        for resource in QUOTAS.combined_resources(context):
      File "nova/quota.py", line 1306, in combined_resources
        resources.update(self.class_resources(context, 'flavors'))
      File "nova/quota.py", line 1296, in class_resources
        context, {}, quota_class)):
      File "nova/quota.py", line 97, in get_class_quotas
        quota_class)
      File "nova/objects/quotas.py", line 481, in get_all_class_by_name
        class_name)
      File "/sapmnt/home/I500815/src/nova/.tox/py27/local/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 987, in wrapper
        with self._transaction_scope(context):
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/sapmnt/home/I500815/src/nova/.tox/py27/local/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 1037, in _transaction_scope
        context=context) as resource:
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/sapmnt/home/I500815/src/nova/.tox/py27/local/lib/python2.7/site-packages/oslo_db/sqlalchemy/enginefacade.py", line 640, in _session
        bind=self.connection, mode=self.mode)
      File "/sapmnt/home/I500815/src/nova/.tox/py27/local/lib/python2.7/site-packages/fixtures/_fixtures/monkeypatch.py", line 89, in avoid_get
        return captured_method(*args, **kwargs)
      File "nova/tests/fixtures.py", line 265, in _poison_configure
        raise Exception('This test uses methods that set internal oslo_db '
    Exception: This test uses methods that set internal oslo_db state, but it does not claim to use the database. This will conflict with the setup of tests that do use the database and cause failures later.

(cherry picked from commit d6ae12628bb3fc175a47c7153355db86bf155958)